metric:
  type: "shell"
  timeout: 10000
  shell:
    entrypoint: "python"
    command:
      - "/run_plugin.py"
      - "metric"
      - "--config"
      - "/etc/custom-pod-autoscaler/config.json"
evaluate:
  type: "shell"
  timeout: 10000
  shell:
    entrypoint: "python"
    command:
      - "/run_plugin.py"
      - "evaluate"
      - "--config"
      - "/etc/custom-pod-autoscaler/config.json"
runMode: "per-resource"
